import type { Metadata } from "next";
import { RootLayout as SharedRootLayout } from "@repo/ui/components";

// App-specific global styles
import "./globals.css";

export const metadata: Metadata = {
  title: "Dingent Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // Pass the children to the shared layout component
  return <SharedRootLayout>{children}</SharedRootLayout>;
}
