import type { Metadata } from "next";
import { fonts } from "@repo/config/fonts";

import "@repo/ui/styles.css";
import { Providers } from "./providers"; // Import the new client component

const geistSans = fonts.sans;
const geistMono = fonts.mono;
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} ${geistMono.className} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
import "./globals.css";
