import type { Metadata } from "next";
import { RootLayout as SharedRootLayout } from "@repo/ui/components";

import "./globals.css";
// import "@copilotkit/react-ui/styles.css";
import "@copilotkit/react-ui/v2/styles.css";

export const metadata: Metadata = {
  title: "Dingent Frontend",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <SharedRootLayout>{children}</SharedRootLayout>;
}
