import type { Metadata } from "next";
import { RootLayout as SharedRootLayout } from "@repo/ui/components";

// App-specific global styles
import "./globals.css";
import "@copilotkit/react-ui/styles.css"; // Keep app-specific CSS here

export const metadata: Metadata = {
  title: "Dingent Frontend",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <SharedRootLayout>{children}</SharedRootLayout>;
}
