llm.model="gpt-4.1"
[[assistants]]
name = "text2sql_assistant"
description = "This is an assistant for text2sql"
enabled = false
tools = [
  { plugin_name = "text2sql", name = "s-text2sql",llm.model="gpt-4.1", database.name="sakila",database.uri="sqlite:///./data/sakila.db"}
]

[[assistants]]
name = "arXiv_assistant"
description = "This is an assistant for arXiv search"
tools = [
  { plugin_name = "arXiv-Searcher", name = "arXiv"}
]
